language: node_js
node_js:
  - node
script:
  - node ./internals/scripts/generate-templates-for-linting
  - npm test -- --maxWorkers=4
  - npm run build
before_install:
  - openssl aes-256-cbc -K $encrypted_9a752479e76f_key -iv $encrypted_9a752479e76f_iv
    -in xperience.enc -out ~/.ssh/xperience -d
  - eval "$(ssh-agent -s)"
  - chmod 600 ~/.ssh/xperience
  - ssh-add ~/.ssh/xperience
  - cat ~/.ssh/known_hosts
  - echo > ~/.ssh/known_hosts
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
notifications:
  email:
    on_failure: change
after_success: 
  - sh ./deploy.sh
cache:
  directories:
    - node_modules
    - ~/.ssh
